title: Stefan Garlonta's learning blog
author: Stefan Garlonta
email: garlontas@noreply.github.com
description: > # this means to ignore newlines until "baseurl:"
  My Github Learning Lab blog

# social links
github_username:  garlontas # DO NOT include the @ character, or else the build will fail!
theme: minima
show_excerpts: true # set to false to remove excerpts on the homepage
